### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by mehrdad2000** [adelbs/ISO8583#34]
C:\temp> java -jar ".\ISO8583-master\target\Adelbs-ISO8583-1.6.0.jar"
Exception in thread "main" java.lang.NullPointerException
        at sun.awt.SunToolkit.getImageFromHash(Unknown Source)
        at sun.awt.SunToolkit.getImage(Unknown Source)
        at org.adelbs.iso8583.Main.<init>(Main.java:50)
        at org.adelbs.iso8583.Main.main(Main.java:25)

C:\temp>>java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

Windows 10

any idea? 
Thanks,

**Comment by tiagoms1** [comment]
It was related with the image folder that was under src/main/java. I have just commited a new version with the images under src/main/resources. Please take a look and let us know.
